# Generated by Django 3.2 on 2021-05-06 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Monster_Hunter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palico',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Monster_Hunter.hunter'),
        ),
    ]
