# Generated by Django 3.2 on 2021-05-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monster_Hunter', '0002_alter_palico_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunter',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='rank',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monster',
            name='combat_strategy',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='monster',
            name='rank',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='palico',
            name='combat_style',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='palico',
            name='experience_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='palico',
            name='rank',
            field=models.SmallIntegerField(default=0),
        ),
    ]
