# Generated by Django 3.2 on 2021-05-06 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Monster_Hunter', '0004_armor_collected_object_merchantable_object_object_weapon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('object1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monster_Hunter.object')),
            ],
            options={
                'ordering': ['object1'],
            },
        ),
        migrations.CreateModel(
            name='Reward_object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('hunter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monster_Hunter.hunter')),
                ('monster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monster_Hunter.monster')),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monster_Hunter.object')),
            ],
            options={
                'ordering': ['monster_id'],
                'unique_together': {('monster_id', 'hunter_id'), ('object_id', 'hunter_id')},
            },
        ),
        migrations.CreateModel(
            name='Palico_lent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('hunter_lent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monster_Hunter.hunter')),
                ('palico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monster_Hunter.palico')),
            ],
            options={
                'unique_together': {('delivery_date', 'palico_id'), ('delivery_date', 'hunter_lent')},
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('hunter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monster_Hunter.hunter')),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monster_Hunter.object')),
            ],
            options={
                'ordering': ['hunter_id'],
                'unique_together': {('hunter_id', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='Elemental_resistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('element_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monster_Hunter.element')),
                ('monster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monster_Hunter.monster')),
            ],
            options={
                'ordering': ['monster_id'],
                'unique_together': {('monster_id', 'element_id')},
            },
        ),
        migrations.CreateModel(
            name='Elemental_defense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('element_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monster_Hunter.element')),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monster_Hunter.object')),
            ],
            options={
                'ordering': ['object_id'],
                'unique_together': {('object_id', 'element_id')},
            },
        ),
    ]
