# Generated by Django 3.2 on 2021-05-06 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monster_Hunter', '0005_element_elemental_defense_elemental_resistance_inventory_palico_lent_recipes_reward_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='hunter_id',
            new_name='hunter',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='object_id',
            new_name='object',
        ),
    ]
