# Generated by Django 3.2 on 2021-05-06 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monster_Hunter', '0006_auto_20210506_2114'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('hunter_id', 'object_id')},
        ),
    ]
