# Generated by Django 3.2 on 2021-05-19 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Monster_Hunter', '0007_alter_inventory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='object2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='object2', to='Monster_Hunter.object'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='armor',
            name='object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Monster_Hunter.object'),
        ),
        migrations.AlterField(
            model_name='collected_object',
            name='object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Monster_Hunter.object'),
        ),
        migrations.AlterField(
            model_name='merchantable_object',
            name='object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Monster_Hunter.object'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='object1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object1', to='Monster_Hunter.object'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Monster_Hunter.object'),
        ),
        migrations.AlterUniqueTogether(
            name='recipes',
            unique_together={('object1', 'object2')},
        ),
    ]
