# Generated by Django 3.2 on 2021-05-17 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Monster_Hunter', '0009_auto_20210519_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemental_defense',
            name='element_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Monster_Hunter.element'),
        ),
        migrations.AlterField(
            model_name='elemental_resistance',
            name='element_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Monster_Hunter.element'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monster',
            name='max_size',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='monster',
            name='min_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='object2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object2', to='Monster_Hunter.object'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reward_object',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
