# Generated by Django 3.2 on 2021-05-17 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Monster_Hunter', '0010_auto_20210516_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemental_defense',
            name='object_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monster_Hunter.armor'),
        ),
    ]
