# Generated by Django 3.2 on 2021-05-17 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monster_Hunter', '0011_alter_elemental_defense_object_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elemental_defense',
            options={'ordering': ['armor']},
        ),
        migrations.RenameField(
            model_name='elemental_defense',
            old_name='object_id',
            new_name='armor',
        ),
        migrations.RenameField(
            model_name='elemental_defense',
            old_name='element_id',
            new_name='element',
        ),
        migrations.RenameField(
            model_name='elemental_resistance',
            old_name='element_id',
            new_name='element',
        ),
        migrations.RenameField(
            model_name='elemental_resistance',
            old_name='monster_id',
            new_name='monster',
        ),
        migrations.AlterUniqueTogether(
            name='elemental_defense',
            unique_together={('armor', 'element')},
        ),
    ]
