# Generated by Django 3.2 on 2021-05-17 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Monster_Hunter', '0012_auto_20210516_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemental_defense',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monster_Hunter.element'),
        ),
        migrations.AlterUniqueTogether(
            name='elemental_resistance',
            unique_together={('monster_id', 'element_id')},
        ),
    ]
