# Generated by Django 3.2 on 2021-05-17 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Monster_Hunter', '0013_auto_20210517_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monster_Hunter.object'),
        ),
    ]
