# Generated by Django 3.2 on 2021-05-17 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Monster_Hunter', '0014_alter_armor_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemental_resistance',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monster_Hunter.element'),
        ),
        migrations.AlterUniqueTogether(
            name='weapon',
            unique_together={('object', 'weapon_type')},
        ),
        migrations.CreateModel(
            name='Elemental_attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monster_Hunter.element')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monster_Hunter.weapon')),
            ],
            options={
                'ordering': ['weapon'],
                'unique_together': {('weapon', 'element')},
            },
        ),
    ]
