# Generated by Django 3.2 on 2021-05-18 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monster_Hunter', '0015_auto_20210517_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['hunter_id'], 'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterModelOptions(
            name='recipes',
            options={'ordering': ['object1'], 'verbose_name_plural': 'Recipes'},
        ),
        migrations.AlterUniqueTogether(
            name='reward_object',
            unique_together={('monster_id', 'object_id')},
        ),
        migrations.RemoveField(
            model_name='reward_object',
            name='hunter_id',
        ),
    ]
