# Generated by Django 3.2 on 2021-05-18 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monster_Hunter', '0016_auto_20210518_0114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reward_object',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='reward_object',
            unique_together=set(),
        ),
    ]
