# Generated by Django 3.2 on 2021-05-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monster_Hunter', '0019_elemental_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='defense',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
    ]
