# Generated by Django 3.2 on 2021-05-31 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monster_Hunter', '0024_auto_20210531_1802'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='elemental_defense',
            unique_together={('armor', 'element')},
        ),
        migrations.AlterUniqueTogether(
            name='elemental_resistance',
            unique_together={('monster', 'element')},
        ),
    ]
